from typing import Literal

type OficinaRegistral = Literal[
    "ABANCAY",
    "ANDAHUAYLAS",
    "AREQUIPA",
    "AYACUCHO",
    "BAGUA",
    "BARRANCA",
    "CAJAMARCA",
    "CALLAO",
    "CAMANA",
    "CASMA",
    "CASTILLA _ APLAO",
    "CAÑETE",
    "CHACHAPOYAS",
    "CHEPEN",
    "CHICLAYO",
    "CHIMBOTE",
    "CHINCHA",
    "CHOTA",
    "CUSCO",
    "ESPINAR",
    "HUACHO",
    "HUAMACHUCO",
    "HUANCAVELICA",
    "HUANCAYO",
    "HUANTA",
    "HUANUCO",
    "HUARAL",
    "HUARAZ",
    "ICA",
    "ILO",
    "ISLAY _ MOLLENDO",
    "JAEN",
    "JUANJUI",
    "JULIACA",
    "LA MERCED (SELVA CENTRAL)",
    "LIMA",
    "MADRE DE DIOS",
    "MAYNAS",
    "MOQUEGUA",
    "MOYOBAMBA",
    "NAZCA",
    "OTUZCO",
    "PASCO",
    "PISCO",
    "PIURA",
    "PUCALLPA",
    "PUNO",
    "QUILLABAMBA",
    "SAN PEDRO",
    "SATIPO",
    "SICUANI",
    "SULLANA",
    "TACNA",
    "TARAPOTO",
    "TARMA",
    "TINGO MARIA",
    "TRUJILLO",
    "TUMBES",
    "YURIMAGUAS",
]
__oficinas_registrales__ = (
    "ABANCAY",
    "ANDAHUAYLAS",
    "AREQUIPA",
    "AYACUCHO",
    "BAGUA",
    "BARRANCA",
    "CAJAMARCA",
    "CALLAO",
    "CAMANA",
    "CASMA",
    "CASTILLA _ APLAO",
    "CAÑETE",
    "CHACHAPOYAS",
    "CHEPEN",
    "CHICLAYO",
    "CHIMBOTE",
    "CHINCHA",
    "CHOTA",
    "CUSCO",
    "ESPINAR",
    "HUACHO",
    "HUAMACHUCO",
    "HUANCAVELICA",
    "HUANCAYO",
    "HUANTA",
    "HUANUCO",
    "HUARAL",
    "HUARAZ",
    "ICA",
    "ILO",
    "ISLAY _ MOLLENDO",
    "JAEN",
    "JUANJUI",
    "JULIACA",
    "LA MERCED (SELVA CENTRAL)",
    "LIMA",
    "MADRE DE DIOS",
    "MAYNAS",
    "MOQUEGUA",
    "MOYOBAMBA",
    "NAZCA",
    "OTUZCO",
    "PASCO",
    "PISCO",
    "PIURA",
    "PUCALLPA",
    "PUNO",
    "QUILLABAMBA",
    "SAN PEDRO",
    "SATIPO",
    "SICUANI",
    "SULLANA",
    "TACNA",
    "TARAPOTO",
    "TARMA",
    "TINGO MARIA",
    "TRUJILLO",
    "TUMBES",
    "YURIMAGUAS",
)
