from typing import Literal

type TipoDocumento = Literal[
    "CE CARNET DE EXTRANJERIA",
    "PS PASAPORTE",
    "DNI DOCUMENTO NACIONAL DE IDENTIDAD",
    "CAN DOCUMENTO DE IDENTIDAD EXTRANJERO",
    "PTP PERMISO TEMPORAL DE PERMANENCIA",
    "CPP CARNE DE PERMISO TEMPORAL DE PERMANENCIA -CPP",
    "DOI DOCUMENTO OFICIAL DE IDENTIDAD",
]

__tipos_documentos__ = (
    "CE CARNET DE EXTRANJERIA",
    "PS PASAPORTE",
    "DNI DOCUMENTO NACIONAL DE IDENTIDAD",
    "CAN DOCUMENTO DE IDENTIDAD EXTRANJERO",
    "PTP PERMISO TEMPORAL DE PERMANENCIA",
    "CPP CARNE DE PERMISO TEMPORAL DE PERMANENCIA -CPP",
    "DOI DOCUMENTO OFICIAL DE IDENTIDAD",
)

tipo_documento_dict: dict[str, TipoDocumento] = {
    "CARNET DE EXTRANJERIA": "CE CARNET DE EXTRANJERIA",
    "DNI": "DNI DOCUMENTO NACIONAL DE IDENTIDAD",
    "DOCUMENTO NACIONAL DE IDENTIDAD": "DNI DOCUMENTO NACIONAL DE IDENTIDAD",
    "PASAPORTE": "PS PASAPORTE",
    "C.E": "CE CARNET DE EXTRANJERIA",
    "CE:": "CE CARNET DE EXTRANJERIA",
}
